name: Build package

on:
 workflow_dispatch:
 
jobs:
  build_kernel:
    strategy:
      fail-fast: false
      matrix:
        include:
        - branch: ps3-queue-v3.19
        - branch: ps3-queue-v4.19  
        - branch: ps3-queue-v5.19
    runs-on: ubuntu-20.04
    steps:

    - run: sudo apt update && sudo apt install -y binutils-powerpc64le-linux-gnu bc flex bison -y
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ps3-pkg1/ps3-linux
        fetch-depth: 1
        ref: ${{ matrix.branch }}

    - name: Checkout ya2d
      uses: actions/checkout@v4
      with:
        repository: ps3-pkgi/ya2d
        path: ya2d_ps3

    - name: Checkout mini18n
      uses: actions/checkout@v3
      with:
        repository: ps3-pkgi/mini18n
        path: mini18n

    - name: Set env vars
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV

      # using pre-compiled sdk
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz | tar xz -C ./
        curl -sL https://github.com/ps3dev/PSL1GHT/raw/master/ppu/include/sysutil/sysutil.h -o ps3dev/ppu/include/sysutil/sysutil.h

    - name: Install ya2d
      working-directory: ya2d_ps3/libya2d
      run: |
        sudo make install

    - name: Install mini18n
      working-directory: mini18n
      run: |
        sudo make install
    - name: Build
      continue-on-error: true
      run: make ps3_defconfig -j4 && make -j4
      env:
        ARCH: powerpc
        CROSS_COMPILE: "ccache powerpc64le-linux-gnueabi-"
        O: out
    - run: df -h
